version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: on-failure
    command: >
      sh -c "npm start"

  db:
    image: mongo
    env_file:
      - .env
    volumes:
      - ./mongo_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


