export * from "./SimilarDeviceCarousel/SimilarDeviceCarousel"
export * from "./CreateDeviceForm/CreateDeviceForm"
export * from "./PasswordForgot/PasswordForgot"
export * from "./MediaCarousel/MediaCarousel"
export * from "./Categories/Categories"
export * from "./UpButton/UpButton"
export * from "./Footer/Footer"
export * from "./Colors/Colors"
export * from "./Brands/Brands"
export * from "./Header/Header"

export * from "./Device/Device"
export * from "./Banner/Banner"
export * from "./DeviceSorter/DeviceSorter"
export * from "./PaginationDevice/PaginationDevice"
